name: SimpleItemGenerator
version: '${version}'
main: ua.valeriishymchuk.simpleitemgenerator.SimpleItemGeneratorPlugin
softdepend:
  - ItemsAdder
  - PlaceholderAPI
  - HeadDatabase
api-version: 1.13
